### ISSUE TITLE
Drop support for MDAPI format metadata

### ISSUE THREAD

**Issue by kjonescertinia** [apex-dev-tools/apex-ls#97]
We currently support both SFDX and the old MDAPI format metadata. This does not cause any major issues but given SFDX format has been available for quite some time it may be appropriate to consider removing MDAPI support to help simplify. If we were to do this we may also want to consider improving our validation of the location of metadata files in general to match that used by the SFDX libraries.

At the moment a number of samples and unit tests use MDAPI format, we could re-work the tests as needed but the samples would likely just need to be removed.

**Comment by nawforce** [comment]
## Implementation Plan for Dropping MDAPI Support

Based on analysis of the codebase, here's our comprehensive plan to drop MDAPI format support while preserving test coverage by converting tests to SFDX format.

### **Current MDAPI Implementation Analysis**

**Core MDAPI Support:**
- `MDAPIWorkspaceConfig` class in `shared/src/main/scala/com/nawforce/pkgforce/sfdx/WorkspaceConfig.scala:26-41`
- Fallback logic in `Workspace.scala:134` that treats directories without `sfdx-project.json` as MDAPI
- 1 sample using MDAPI format: `samples/mdapi-test/`
- 11+ test files with MDAPI-specific test cases

**Test Coverage:**
- 67 test files use `FileSystemHelper.run()` for virtual file system testing
- Several tests already have both MDAPI and SFDX versions (e.g., `MDIndexFindTest.scala:52-66`)
- Many MDAPI tests validate core functionality that should be preserved

---

## **Phase 1: Enhance FileSystemHelper for SFDX Auto-Creation**

### 1.1 Add `runWithSFDX` Method to FileSystemHelper

**Files to modify:**
- `jvm/src/test/scala/com/nawforce/runtime/FileSystemHelper.scala`
- `js/src/test/scala/com/nawforce/runtime/FileSystemHelper.scala`

**Implementation:**
```scala
def runWithSFDX[T](files: Map[String, String])(verify: Path => T): T = {
  val sfdxFiles = createSFDXStructure(files)
  run(sfdxFiles)(verify)
}

private def createSFDXStructure(files: Map[String, String]): Map[String, String] = {
  // Auto-create sfdx-project.json if not present
  // Move .cls files to force-app/main/default/classes/
  // Move .trigger files to force-app/main/default/triggers/
  // Move other metadata to appropriate SFDX paths
}
```

**Acceptance Criteria:**
- [ ] `runWithSFDX` automatically creates `sfdx-project.json` if not provided
- [ ] Apex classes moved to `force-app/main/default/classes/`
- [ ] Triggers moved to `force-app/main/default/triggers/`
- [ ] Other metadata types placed in correct SFDX paths
- [ ] Preserves existing SFDX structure if `sfdx-project.json` already exists
- [ ] Both JVM and JS versions updated

### 1.2 Test the Enhanced FileSystemHelper

**Test Cases:**
- [ ] Auto-creates basic SFDX project structure
- [ ] Preserves existing SFDX structure when provided
- [ ] Correctly moves various metadata types to SFDX paths
- [ ] Works with both JVM and JS platforms

---

## **Phase 2: Convert MDAPI Tests to SFDX Format**

### 2.1 Convert Core MDIndex Tests

**Files to convert:**
- [ ] `jvm/src/test/scala/com/nawforce/runtime/api/MDIndexFindTest.scala`
  - Convert "MDAPI class is loaded" and similar tests to use `runWithSFDX`
  - Remove redundant tests that already have SFDX equivalents
  - Rename remaining tests to remove "MDAPI" references
  
- [ ] `jvm/src/test/scala/com/nawforce/runtime/api/MDIndexPlatformTest.scala`
  - Convert platform loading tests to SFDX format
  - Update test descriptions

### 2.2 Convert RefreshSObjectTest MDAPI Cases

**File:** `jvm/src/test/scala/com/nawforce/apexlink/pkg/RefreshSObjectTest.scala`

**Tests to convert:**
- [ ] "MDAPI delete" test (line 347)
- [ ] "MDAPI lookup removed target" test (line 392) 
- [ ] "Custom Metadata MDAPI delete" test (line 870)
- [ ] "Platform event MDAPI delete" test (line 1040)
- [ ] "Big object MDAPI delete" test (line 1210)

### 2.3 Convert OrgAPITest Cases

**File:** `jvm/src/test/scala/com/nawforce/apexlink/rpc/OrgAPITest.scala`

**Tests using `mdapi-test` sample:**
- [ ] "Open MDAPI directory" test (line 105)
- [ ] Update all tests referencing `samplesDir.join("mdapi-test")` to use SFDX structure
- [ ] Create equivalent SFDX test data instead of using `mdapi-test` sample

### 2.4 Convert Additional MDAPI Test Cases

**Files with MDAPI tests to convert:**
- [ ] `jvm/src/test/scala/com/nawforce/apexlink/pkg/DependentProjectTest.scala` - "MDAPI dependent" test
- [ ] `jvm/src/test/scala/com/nawforce/apexlink/types/CustomObjectTest.scala` - "Extended SObject reference (1GP MDAPI)" test
- [ ] `jvm/src/test/scala/com/nawforce/apexlink/types/InterviewTest.scala` - "Create flow (MDAPI)" test
- [ ] `shared/src/test/scala/com/nawforce/pkgforce/sfdx/ProjectLayerTest.scala` - "Single packageDirectory with external MDAPI package" test
- [ ] `shared/src/test/scala/com/nawforce/pkgforce/workspace/WorkspaceTest.scala` - "MDAPI workspace (no sfdx-project.json) has no external path filter" test

---

## **Phase 3: Remove Core MDAPI Support**

### 3.1 Remove MDAPIWorkspaceConfig Class

**File:** `shared/src/main/scala/com/nawforce/pkgforce/sfdx/WorkspaceConfig.scala`
- [ ] Delete `MDAPIWorkspaceConfig` class (lines 26-41)
- [ ] Update imports in dependent files

### 3.2 Update Workspace Creation Logic

**File:** `shared/src/main/scala/com/nawforce/pkgforce/workspace/Workspace.scala`
- [ ] Remove fallback to `MDAPIWorkspaceConfig` in `loadWorkspaceConfig()` (line 134)
- [ ] Make `sfdx-project.json` requirement mandatory
- [ ] Return `None` if `sfdx-project.json` not found instead of creating MDAPI workspace
- [ ] Remove `MDAPIWorkspaceConfig` from imports (line 21)
- [ ] Update pattern matching in `apply` method (lines 80-88) to remove MDAPI case

### 3.3 Update Org.scala Import

**File:** `jvm/src/main/scala/com/nawforce/apexlink/api/Org.scala`
- [ ] Remove `MDAPIWorkspaceConfig` from imports (line 23)

### 3.4 Update Documentation References

**Files to update:**
- [ ] Remove MDAPI references from inline code comments
- [ ] Update `DocumentIndex.scala:177` comment about "MDAPI only projects"

---

## **Phase 4: Enhanced SFDX Validation & Error Messages**

### 4.1 Improve Project Structure Validation

**File:** `shared/src/main/scala/com/nawforce/pkgforce/workspace/Workspace.scala`

**Enhancements:**
- [ ] Add validation that metadata files are in correct SFDX locations
- [ ] Reject projects with loose metadata files in root directory
- [ ] Validate packageDirectory paths exist and contain valid structure

### 4.2 Enhanced Error Messages

- [ ] Provide clear error messages when MDAPI-style projects are detected
- [ ] Guide users to migrate to SFDX format
- [ ] Reference official Salesforce migration documentation

---

## **Phase 5: Sample and Documentation Cleanup**

### 5.1 Remove MDAPI Sample

- [ ] Delete `samples/mdapi-test/` directory entirely
  - `Hello.cls`, `Hello.cls-meta.xml`, `World.cls`, `World.cls-meta.xml`

### 5.2 Update Build and Test Scripts

- [ ] Ensure all tests pass after MDAPI removal
- [ ] Run `sbt test` to validate test conversions
- [ ] Run `sbt scalafmtAll` for code formatting
- [ ] Update any documentation or README files

### 5.3 Breaking Change Documentation

- [ ] Update CHANGELOG with breaking changes
- [ ] Document SFDX-only requirement
- [ ] Provide migration guidance for users with MDAPI projects

---

## **Validation & Testing**

### Final Validation Checklist

- [ ] All tests pass: `sbt test`
- [ ] Code formatting: `sbt scalafmtAll` 
- [ ] No references to MDAPI remain in codebase
- [ ] SFDX projects work correctly
- [ ] Projects without `sfdx-project.json` are properly rejected with helpful error messages
- [ ] Test coverage maintained or improved

### Manual Testing

- [ ] Test with various SFDX project structures
- [ ] Test error handling for non-SFDX projects
- [ ] Validate that all converted tests provide equivalent coverage

---

**Estimated Timeline:** 2-3 weeks depending on complexity of test conversions

**Breaking Change:** Yes - requires major version bump and user communication

This plan preserves all existing test coverage while achieving the goal of simplifying the codebase by removing MDAPI support.
